# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-docstring-first

-   repo: https://github.com/pycqa/pydocstyle
    rev: 5.0.2  # pick a git hash / tag to point to
    hooks:
    -   id: pydocstyle

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1  # pick a git hash / tag to point to
    hooks:
    -   id: rst-backticks

-   repo: https://github.com/amperser/proselint
    rev: 0.10.2
    hooks:
    -   id: proselint

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy
        additional_dependencies: [tokenize-rt==3.2.0]
