# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    # branches: [ master ]
  pull_request:
    # branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy
        pip install proselint
        pip install -e .
        if [ -f requirements/test_requirements.txt ]; then pip install -r requirements/test_requirements.txt; fi
    - name: Check types with mypy
      run: |
        mypy -p pypresseportal
    - name: Test with pytest
      run: |
        pytest
    - name: Check text with proselint
      run: |
        proselint docs/*rst
